In [3]:
import numpy as np

In [7]:
x = np.array([1,2,3,4])
print(x)

y = np.array([[2,3,4],[1,2,5]])  # 행렬생성 but 다른방법이 많아 잘쓰지 않음
print(y)


[1 2 3 4]
[[2 3 4]
 [1 2 5]]


# np.arange 함수로 생성하기 # range와 비슷

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

# np.ones(모든원소1), np.zeros(모든원소0) 로 생성하기

In [19]:
np.ones((4,5))  # 튜플을 활용

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((2,3,4))  # 2개의 3행 4열 행렬 생성 3차원

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.zeros((4,5))  # 튜플을 활용

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# np.empty, np.full 로 생성하기

In [38]:
np.empty(( 3,4)) # 초기화된 값 적용

array([[1.50671072e-312, 0.00000000e+000, 8.76794447e+252,
        2.15895723e+227],
       [6.48224638e+170, 3.67145870e+228, 8.05070409e-096,
        9.03292329e+271],
       [9.08366793e+223, 1.41075687e+232, 1.16070543e-028,
        2.29179605e-312]])

In [23]:
np.full((3,4), 7) # 7로만 이루어진 행렬

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

 # np.eye로 생성하기
 - 단위행렬 생성

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

 # np.linspace로 생성하기

In [26]:
np.linspace(1,10,5) # 1과 10 사이에 숫자 생성(등차)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# reshape 함수활용
 - ndarray의 형태, 차원을 바꾸기위해 사용

In [36]:
x = np.arange(1,16)
print(x)

x.shape

x.reshape(5,3)
# x.reshape(5,4) # 오류발생

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])