## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [6]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.89743677 0.10166075 0.89803173 0.89201046 0.32600497]
 [0.61220368 0.89361056 0.3078661  0.58286047 0.30910002]
 [0.4141186  0.97959599 0.97257668 0.65571948 0.81072849]]


In [7]:
x + y

array([[ 0.89743677,  1.10166075,  2.89803173,  3.89201046,  4.32600497],
       [ 5.61220368,  6.89361056,  7.3078661 ,  8.58286047,  9.30910002],
       [10.4141186 , 11.97959599, 12.97257668, 13.65571948, 14.81072849]])

* Scalar(상수)와의 연산

In [10]:
x + 2  # 모든 원소에 적용

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

* Shape이 다른 경우 연산

In [15]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1,3)

print(a);print(b);print(c);print(d)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [12]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [17]:
a + c # 뒷차원을 비교하기때문에 연산이 안됨

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [18]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])