## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [3]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [7]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.34901854 0.90686389 0.68975819 0.83698402 0.70217821]
 [0.67425869 0.47548593 0.05390864 0.5681243  0.419021  ]
 [0.49822563 0.53264458 0.40505164 0.12621054 0.53223157]]


#### 연산 함수
 - add, subtract, multiply, divide

In [8]:
np.add(x,y) # 똑같은 위치끼리 더해줌, 차원이 다르면 안됨

array([[ 0.34901854,  1.90686389,  2.68975819,  3.83698402,  4.70217821],
       [ 5.67425869,  6.47548593,  7.05390864,  8.5681243 ,  9.419021  ],
       [10.49822563, 11.53264458, 12.40505164, 13.12621054, 14.53223157]])

In [10]:
np.multiply(x,y)

array([[0.        , 0.90686389, 1.37951637, 2.51095205, 2.80871284],
       [3.37129347, 2.8529156 , 0.37736046, 4.54499443, 3.77118904],
       [4.98225633, 5.85909035, 4.86061966, 1.64073706, 7.45124199]])

In [12]:
np.subtract(x,y)

array([[-0.34901854,  0.09313611,  1.31024181,  2.16301598,  3.29782179],
       [ 4.32574131,  5.52451407,  6.94609136,  7.4318757 ,  8.580979  ],
       [ 9.50177437, 10.46735542, 11.59494836, 12.87378946, 13.46776843]])

In [13]:
x - y

array([[-0.34901854,  0.09313611,  1.31024181,  2.16301598,  3.29782179],
       [ 4.32574131,  5.52451407,  6.94609136,  7.4318757 ,  8.580979  ],
       [ 9.50177437, 10.46735542, 11.59494836, 12.87378946, 13.46776843]])

In [14]:
x+y

array([[ 0.34901854,  1.90686389,  2.68975819,  3.83698402,  4.70217821],
       [ 5.67425869,  6.47548593,  7.05390864,  8.5681243 ,  9.419021  ],
       [10.49822563, 11.53264458, 12.40505164, 13.12621054, 14.53223157]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [18]:
print(y)

[[0.34901854 0.90686389 0.68975819 0.83698402 0.70217821]
 [0.67425869 0.47548593 0.05390864 0.5681243  0.419021  ]
 [0.49822563 0.53264458 0.40505164 0.12621054 0.53223157]]


In [19]:
np.mean(y)

0.5179976920864857

In [21]:
y.mean()

0.5179976920864857

In [22]:
np.max(y)

0.9068638909939765

In [23]:
np.median(y)

0.5322315704315704

In [24]:
np.argmax(y)  # 맥스값의 위치 표시

1

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [28]:
y

array([[0.34901854, 0.90686389, 0.68975819, 0.83698402, 0.70217821],
       [0.67425869, 0.47548593, 0.05390864, 0.5681243 , 0.419021  ],
       [0.49822563, 0.53264458, 0.40505164, 0.12621054, 0.53223157]])

In [30]:
sum(y)  # 컬럼을 중심으로 합계

array([1.52150287, 1.9149944 , 1.14871846, 1.53131886, 1.65343078])

In [31]:
np.sum(y)

7.769965381297286

In [33]:
np.sum(y, axis=0)  # axis default : None, 0 : 컬럼기준 , 1: 행기준

array([1.52150287, 1.9149944 , 1.14871846, 1.53131886, 1.65343078])

In [27]:
np.cumsum(y)

array([0.34901854, 1.25588243, 1.94564062, 2.78262464, 3.48480285,
       4.15906154, 4.63454747, 4.68845611, 5.25658042, 5.67560142,
       6.17382705, 6.70647163, 7.11152327, 7.23773381, 7.76996538])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [35]:
z = np.random.randn(10)
print(z)

[-0.7481658  -1.53893038 -1.35557787  0.02649996  1.76970033  0.80968463
  0.43590466 -0.41193936 -0.09963173  0.54358516]


In [37]:
z>0

array([False, False, False,  True,  True,  True,  True, False, False,
        True])

In [39]:
np.any(z>0), np.all(z>0), np.all(z!=0)

(True, False, True)

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [40]:
z = np.random.randn(10)
print(z)

[ 1.17101398 -1.07214504  0.0845043   1.60156719  0.23683934  0.60915827
 -0.8541417   0.14482016  0.88515919  0.85617914]


In [43]:
np.where(z>0,z,0)

array([1.17101398, 0.        , 0.0845043 , 1.60156719, 0.23683934,
       0.60915827, 0.        , 0.14482016, 0.88515919, 0.85617914])