## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [4]:
x = np.random.rand(3,3); print(x)

[[0.576543   0.66835306 0.62218732]
 [0.40725555 0.17047153 0.87528455]
 [0.03659545 0.02123403 0.73438707]]


In [10]:
inv_x = np.linalg.inv(x)
print(inv_x)

[[-0.92281578  4.13440705 -4.14579515]
 [ 2.31168018 -3.46802953  2.17489476]
 [-0.02085472 -0.10574836  1.50538522]]


In [11]:
x @ inv_x

array([[ 1.00000000e+00,  2.24541202e-16, -1.28656850e-16],
       [ 1.17858245e-16,  1.00000000e+00, -1.65792901e-16],
       [-9.68302804e-19,  9.55845042e-19,  1.00000000e+00]])

In [12]:
np.matmul(x, inv_x)

array([[ 1.00000000e+00,  2.24541202e-16, -1.28656850e-16],
       [ 1.17858245e-16,  1.00000000e+00, -1.65792901e-16],
       [-9.68302804e-19,  9.55845042e-19,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [23]:
A = np.array([[1,1],[2,4]])
B = np.array([25,64])

print(A); print(B)

x = np.linalg.solve(A,B)
print(x)



[[1 1]
 [2 4]]
[25 64]
[18.  7.]


array([25., 64.])

In [27]:
print(A @ x)
print(np.allclose(A@x, B))

[25. 64.]
True
